### ISSUE TITLE
argparse: potential version mismatch or bug

### ISSUE THREAD

**Issue by rawilder** [withfig/autocomplete-tools#78] opened 2022-09-27 20:05 UTC
I've been trying to implement the argparse fig autocomplete with a relatively simple example.

```python3
parser = argparse.ArgumentParser(description='process yaml file.')
parser.add_argument('-f', '--file', type=str, help='yaml file to process')
add_completion_spec_command(parser)
args = parser.parse_args()
```

And when I run it I get the following error:
```bash
python3 example.py --generate-fig-spec
Traceback (most recent call last):
  File "~/scripts/example.py", line 7, in <module>
    add_completion_spec_command(parser)
  File "/usr/local/lib/python3.10/site-packages/argparse_complete_fig/fig.py", line 206, in add_completion_spec_command
    parser.add_argument(action=GenerateFigSpecAction)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1405, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
TypeError: _ActionsContainer._get_positional_kwargs() missing 1 required positional argument: 'dest'
```

**Comment by fedeci** [comment] 2023-04-15 15:04
@rawilder, I have just released a fix for this! https://pypi.org/project/argparse-complete-fig/1.0.1/

**Comment by fedeci** [comment] 2023-04-15 15:04
duplicate of #87

**Closed by fedeci** 2023-04-15 15:04 UTC
